<?php
$arrProvinces;

function GetProvinceList(){
    if(isset($arrProvinces))
        return $arrProvinces;
    $arrProvinces=array();
ThemVung( "An Giang","3536.7");
ThemVung( "Bà Rịa - Vũng Tàu","1989.5");
ThemVung( "Bắc Giang","3844");
ThemVung( "Bắc Kạn","4859.4");
ThemVung( "Bạc Liêu","2468.7");
ThemVung( "Bắc Ninh","822.7");
ThemVung( "Bến Tre","2360.6");
ThemVung( "Bình Định","6050.6");
ThemVung( "Bình Dương","2694.4");
ThemVung( "Bình Phước","6871.5");
ThemVung( "Bình Thuận","7812.9");
ThemVung( "Cà Mau","5294.9");
ThemVung( "Cần Thơ","1409");
ThemVung( "Cao Bằng","6707.9");
ThemVung( "Đà Nẵng","1285.4");
ThemVung( "Đắk Lắk","13125.4");
ThemVung( "Đắk Nông","6515.6");
ThemVung( "Điện Biên","9562.9");
ThemVung( "Đồng Nai","5907.2");
ThemVung( "Đồng Tháp","3377");
ThemVung( "Gia Lai","15536.9");
ThemVung( "Hà Giang","7914.9");
ThemVung( "Hà Nam","860.5");
ThemVung( "Hà Nội","3328.9");
ThemVung( "Hà Tĩnh","5997.2");
ThemVung( "Hải Dương","1656");
ThemVung( "Hải Phòng","1523.4");
ThemVung( "Hậu Giang","1602.5");
ThemVung( "Hoà Bình","4608.7");
ThemVung( "Hưng Yên","926");
ThemVung( "Khánh Hoà","5217.7");
ThemVung( "Kiên Giang","6348.5");
ThemVung( "Kon Tum","9689.6");
ThemVung( "Lai Châu","9068.8");
ThemVung( "Lâm Đồng","9773.5");
ThemVung( "Lạng Sơn","8320.8");
ThemVung( "Lào Cai","6383.9");
ThemVung( "Long An","4492.4");
ThemVung( "Nam Định","1651.4");
ThemVung( "Nghệ An","16493.7");
ThemVung( "Ninh Bình","1390.3");
ThemVung( "Ninh Thuận","3358.3");
ThemVung( "Phú Thọ","3533.4");
ThemVung( "Phú Yên","5060.6");
ThemVung( "Quảng Bình","8065.3");
ThemVung( "Quảng Nam","10438.4");
ThemVung( "Quảng Ngãi","5153");
ThemVung( "Quảng Ninh","6102.4");
ThemVung( "Quảng Trị","4739.8");
ThemVung( "Sóc Trăng","3311.6");
ThemVung( "Sơn La","14174.4");
ThemVung( "Tây Ninh","4039.7");
ThemVung( "Thái Bình","1570");
ThemVung( "Thái Nguyên","3531.7");
ThemVung( "Thanh Hoá","11131.9");
ThemVung( "Thừa Thiên Huế","5033.2");
ThemVung( "Tiền Giang","2508.3");
ThemVung( "TP Hồ Chí Minh","2095.6");
ThemVung( "Trà Vinh","2341.2");
ThemVung( "Tuyên Quang","5867.3");
ThemVung( "Vĩnh Long","1496.8");
ThemVung( "Vĩnh Phúc","1236.5");
ThemVung( "Yên Bái","6886.3");
ThemVung( "Toàn Quốc","331210");
return $arrProvinces;
// echo "Hoàn tất cập nhật danh sách vùng";
}

//--------------------------------------------------------------
//ThemDichVu( "Âm nhạc");
//ThemDichVu( "An ninh");
//ThemDichVu( "Bãi đỗ xe hơi");
//ThemDichVu( "Bãi đỗ xe máy");
//ThemDichVu( "Bảng điện tử led");
//ThemDichVu( "Bảng hiệu, bảng quảng cáo, chữ nổi, kệ trưng bày");
//ThemDichVu( "Bệnh viện");
//ThemDichVu( "Bida");
//ThemDichVu( "Cao Đẳng");
//ThemDichVu( "Cây cảnh");
//ThemDichVu( "Cây giống");
//ThemDichVu( "Chăm sóc cây cảnh");
//ThemDichVu( "Chăm sóc người già");
//ThemDichVu( "Chăm sóc sức khỏe tại nhà");
//ThemDichVu( "Chăm sóc tại gia");
//ThemDichVu( "Chăm sóc thú cưng");
//ThemDichVu( "Chỗ ở");
//ThemDichVu( "Chợ");
//ThemDichVu( "Công Chứng Tại Nhà");
//ThemDichVu( "Công ty bảo vệ");
//ThemDichVu( "Cửa hàng bán đồ lưu niệm");
//ThemDichVu( "Cửa hàng bán đồ thể thao");
//ThemDichVu( "Cửa hàng bán hoa");
//ThemDichVu( "Cửa hàng bánh kẹo");
//ThemDichVu( "Cửa hàng Điện cơ");
//ThemDichVu( "Cửa hàng Điện tử gia dụng");
//ThemDichVu( "Cửa hàng Điện tử văn phòng");
//ThemDichVu( "Cửa hàng đồ gỗ cũ");
//ThemDichVu( "Cửa hàng đồ gỗ");
//ThemDichVu( "Cửa hàng đồng hồ");
//ThemDichVu( "Cửa hàng giày dép");
//ThemDichVu( "Cửa hàng két sắt");
//ThemDichVu( "Cửa hàng mắt kính");
//ThemDichVu( "Cửa hàng máy quay phim, chụp hình");
//ThemDichVu( "Cửa hàng mũ bảo hiểm");
//ThemDichVu( "Cửa hàng mỹ phẩm");
//ThemDichVu( "Cửa hàng nông nghiệp");
//ThemDichVu( "Cửa hàng phụ kiện xe hơi");
//ThemDichVu( "Cửa hàng phụ kiện xe maý");
//ThemDichVu( "Cửa hàng quần áo");
//ThemDichVu( "Cửa hàng tạp hóa gia đình");
//ThemDichVu( "Cửa hàng thiết bị báo động chống trộm");
//ThemDichVu( "Cửa hàng thú cưng");
//ThemDichVu( "Cửa hàng thực phẩm thú cưng");
//ThemDichVu( "Cửa hàng tiện lợi");
//ThemDichVu( "Cửa hàng trang sức");
//ThemDichVu( "Cửa hàng và dịch vụ quảng cáo ");
//ThemDichVu( "Cửa hàng xe đạp");
//ThemDichVu( "Cửa hàng xe hơi cũ");
//ThemDichVu( "Cửa hàng xe hơi");
//ThemDichVu( "Cửa hàng xe máy cũ");
//ThemDichVu( "Cửa hàng xe máy");
//ThemDichVu( "Đại học");
//ThemDichVu( "Dịch vụ ăn uống");
//ThemDichVu( "Dịch vụ chăm sóc bệnh tại nhà");
//ThemDichVu( "Dịch vụ chăm sóc sau sinh tại nhà");
//ThemDichVu( "Dịch vụ chuyển nhà trọn gói");
//ThemDichVu( "Dịch vụ làm đẹp tại nhà: Móng");
//ThemDichVu( "Dịch vụ làm đẹp tại nhà: Tóc");
//ThemDichVu( "Dịch vụ làm đẹp tại nhà: Trang điểm");
//ThemDichVu( "Dịch vụ pháp lý tại nhà");
//ThemDichVu( "Dịch vụ pháp lý");
//ThemDichVu( "Dịch vụ sửa chăm sóc xe hơi tại nhà");
//ThemDichVu( "Dịch vụ sửa chữa bảo dưỡng máy lạnh tại nhà");
//ThemDichVu( "Dịch vụ sửa chữa bảo dưỡng thiết bị điện tử gia đình tại nhà");
//ThemDichVu( "Dịch vụ sửa chữa điện nước tại nhà");
//ThemDichVu( "Dịch vụ tư vấn pháp luật ở nhà");
//ThemDichVu( "Điện thoại/Máy tính/Laptop");
//ThemDichVu( "Du lịch");
//ThemDichVu( "Dụng cụ/thiết bị công trình xây dựng cho thuê");
//ThemDichVu( "Game");
//ThemDichVu( "Gia sư tại nhà");
//ThemDichVu( "Giải trí");
//ThemDichVu( "Giao hàng");
//ThemDichVu( "Giặt Thảm / Giường / Nệm / Rèm / ở nhà");
//ThemDichVu( "Giúp việc nhà");
//ThemDichVu( "Hàng điện tử");
//ThemDichVu( "Hàng rong");
//ThemDichVu( "Hạt giống");
//ThemDichVu( "Hiệu cắt tóc");
//ThemDichVu( "Hồ bơi");
//ThemDichVu( "Hóa học");
//ThemDichVu( "Home Stay theo ngày");
//ThemDichVu( "Huấn luyện viên Thể dục - Thể thao");
//ThemDichVu( "Hướng dẫn viên");
//ThemDichVu( "Hút hầm cầu");
//ThemDichVu( "Karaoke");
//ThemDichVu( "Khách sạn 01 sao");
//ThemDichVu( "Khách sạn 02 sao");
//ThemDichVu( "Khách sạn 03 sao");
//ThemDichVu( "Khách sạn 04 sao");
//ThemDichVu( "Khách sạn 05 sao");
//ThemDichVu( "Khách sạn không đánh sao");
//ThemDichVu( "Khu giải trí cho trẻ em");
//ThemDichVu( "Làm đẹp");
//ThemDichVu( "Lều/trại - Túi ngủ - Võng");
//ThemDichVu( "Mát Xa Tại Nhà");
//ThemDichVu( "Mẹ và bé");
//ThemDichVu( "Móng");
//ThemDichVu( "Nấu tiệc tại nhà");
//ThemDichVu( "Ngôn ngữ học");
//ThemDichVu( "Nhà / biệt thự cho thuê theo ngày");
//ThemDichVu( "Nhà / biệt thự cho thuê theo tháng");
//ThemDichVu( "Nhà hàng");
//ThemDichVu( "Nha sĩ");
//ThemDichVu( "Nhà trẻ");
//ThemDichVu( "Nhân viên tiếp thị");
//ThemDichVu( "Nước giải khát");
//ThemDichVu( "Phân bón");
//ThemDichVu( "Phòng cho thuê theo giờ");
//ThemDichVu( "Phòng cho thuê theo ngày");
//ThemDichVu( "Phòng cho thuê theo tháng");
//ThemDichVu( "Phòng dạy Thiền");
//ThemDichVu( "Phòng dạy võ");
//ThemDichVu( "Phòng dạy Yoga");
//ThemDichVu( "Phòng GYM");
//ThemDichVu( "Phụ Kiện Thời Trang");
//ThemDichVu( "Quán ăn gia đình");
//ThemDichVu( "Quán bar");
//ThemDichVu( "Quán cà phê");
//ThemDichVu( "Rao vặt: Đất bán");
//ThemDichVu( "Rao vặt: Điện thoại/Máy tính/Laptop");
//ThemDichVu( "Rao vặt: đồ gỗ");
//ThemDichVu( "Rao vặt: máy quay phim, chụp hình");
//ThemDichVu( "Rao vặt: Nhà bán");
//ThemDichVu( "Rao vặt: xe hơi cũ");
//ThemDichVu( "Rao vặt: xe máy cũ");
//ThemDichVu( "Rạp chiếu phim");
//ThemDichVu( "Rau");
//ThemDichVu( "Rượu");
//ThemDichVu( "Sân Cầu lông");
//ThemDichVu( "Sân Quần vợt");
//ThemDichVu( "Siêu thị");
//ThemDichVu( "Sinh vật học");
//ThemDichVu( "Spa");
//ThemDichVu( "Sử");
//ThemDichVu( "Sửa chữa và bảo dưỡng xe hơi lưu động");
//ThemDichVu( "Sửa chữa và bảo dưỡng xe máy lưu động");
//ThemDichVu( "Sức khỏe");
//ThemDichVu( "Tài xế");
//ThemDichVu( "Tạp hóa");
//ThemDichVu( "Taxi");
//ThemDichVu( "Thám tử tư");
//ThemDichVu( "Thể thao");
//ThemDichVu( "Thiết kế nội thất");
//ThemDichVu( "Thiết kế và thi công quản cáo");
//ThemDichVu( "Thợ gỗ");
//ThemDichVu( "Thợ hồ");
//ThemDichVu( "Thợ may");
//ThemDichVu( "Thời trang");
//ThemDichVu( "Thú cưng");
//ThemDichVu( "Thú y");
//ThemDichVu( "Thừa phát lại");
//ThemDichVu( "Thức ăn đông lạnh");
//ThemDichVu( "Thức ăn gia súc, gia cầm");
//ThemDichVu( "Thực phẩm biển");
//ThemDichVu( "Thực phẩm chưa chế biến");
//ThemDichVu( "Thức uống");
//ThemDichVu( "Thuốc bảo vệ thực vật");
//ThemDichVu( "Tiệm Giặt ủi");
//ThemDichVu( "Tiệm sửa chữa và bảo dưỡng xe hơi");
//ThemDichVu( "Tiệm sửa chữa và bảo dưỡng xe máy");
//ThemDichVu( "Tiệm thuốc");
//ThemDichVu( "Tổ chức sự kiệ");
//ThemDichVu( "Toán học");
//ThemDichVu( "Tóc");
//ThemDichVu( "Trái cây");
//ThemDichVu( "Trạm xá");
//ThemDichVu( "Trang Điểm");
//ThemDichVu( "Trồng rau sạch tại nhà");
//ThemDichVu( "Trông trẻ em");
//ThemDichVu( "Trung tâm gia sư");
//ThemDichVu( "Trung tâm ngoại ngữ");
//ThemDichVu( "Trường cấp 1");
//ThemDichVu( "Trường cấp 2");
//ThemDichVu( "Trường cấp 3");
//ThemDichVu( "Trường");
//ThemDichVu( "Vận chuyển");
//ThemDichVu( "Văn học");
//ThemDichVu( "Văn phòng công chứng");
//ThemDichVu( "Văn phòng dịch thuật");
//ThemDichVu( "Văn phòng hướng dẫn viên");
//ThemDichVu( "Văn phòng luật sư");
//ThemDichVu( "Vật lý học");
//ThemDichVu( "Vệ sĩ");
//ThemDichVu( "Vé tàu xe máy bay");
//ThemDichVu( "Xăng");
//ThemDichVu( "Xây dựng");
//ThemDichVu( "Xe ba bánh");
//ThemDichVu( "Xe cho thuê");
//ThemDichVu( "Xe cộ");
//ThemDichVu( "Xe công trình xây dựng cho thuê");
//ThemDichVu( "Xe đạp");
//ThemDichVu( "Xe hơi bảy chổ");
//ThemDichVu( "Xe hơi bốn chổ");
//ThemDichVu( "Xe khách nhỏ");
//ThemDichVu( "Xe khách");
//ThemDichVu( "Xe máy");
//ThemDichVu( "Xe ôm");
//ThemDichVu( "Xe tải");
//ThemDichVu( "Xét nghiệm tại nhà");

//echo "Hoàn tất cập nhật danh sách dịch vụ";
//--------------------------------------------------
// function
function ThemVung($ten, $dt) {
	array_push($GLOBALS['arrProvinces'], $ten);   
 }
 function ThemDichVu($ten) {
 }
}
?>
